### ISSUE TITLE
[Enhancement] /ban & /tempban

### ISSUE THREAD

**Issue by Hatventures** [Cube-Space/geSuit#12]
1) It should be allowed to ban players (for instance accepting UUIDs or nickname.. Nicknames wont be 100% but easy to do as a quick reaction) that have never visited the server.
Right now, it just gives an error feedback: Player not found

2) Slight change/addition in the /tempban syntax
Most ban plugins (well, i've never seen a different syntax) handles the duration of a tempban with the following syntax:

t:2d3h5m //duration: 2 days 3 hours 5 minutes

It is more elegant and natural. And you have no idea how high is the % of the failed tempban on my servers since bungeesuite :P

<3

**Comment by geNAZt** [comment]
geSuitBans change: https://github.com/Cube-Space/geSuitBans/commit/aa5b0318311fc5026c8b116c8f5ad76017db32a4
