### ISSUE TITLE
/mail NPE

### ISSUE THREAD

**Issue by Absentee23** [Cube-Space/geSuit#15]
I received the mail just fine, but wanted to point this out just in case it causes issues for other people.
http://pastebin.com/jcDSL3Nj
(obviously I've got a separate issue to fix too, from the message... :-1: )

**Comment by geNAZt** [comment]
Well /mail is not part of geSuit. Its part of CloudChat and there seem to be no error in saving that Mail the Player sent. 

For the other part its a Bug in Teleportion request which timed out because the Sender left the game.
