### ISSUE TITLE
CloudChat discovery

### ISSUE THREAD

**Issue by Hatventures** [Cube-Space/geSuit#18]
Maybe add somekind of detection of CloudChat from geSuite:
- CloudChat discovered
- CloudChat is NOT configured (brand new install)
- geSuite (maybe add a message on op login, giving a command) is able to autoconfigure it to match the default bungeeSuite channels (namely  local, global, server, and admin)

Would make it very easy for people to move to geSuite.

Could also be a bad 1am idea :P

**Comment by geNAZt** [comment]
And what would that give ? Why should i not implement a better default Config in CloudChat ?

**Comment by Hatventures** [comment]
Just trying to facilitate the migration. Dont read more than that into it

**Comment by geNAZt** [comment]
Oh you mean when someone want to migrate from a BungeeSuite into the CloudChat. That may be possible. Never looked into BungeeSuiteChat that much

**Comment by Hatventures** [comment]
Yes. Basicaly, if they want to migrate to geSuit, a problem arrise. There's no getSuitChat. Panic. CloudChat is MUCH more complicated (and much more powerful). So why not ease them in.
"install cloudchat, it will work like bungeeSuiteChat out of the box, and then do much more..."

**Comment by geNAZt** [comment]
This will be part of CloudChat 8.1.0
