### ISSUE TITLE
Exception encountered when loading plugin: geSuit

### ISSUE THREAD

**Issue by JamieKG** [Cube-Space/geSuit#19]
Hi geNAZt updated plugins on server today and im now getting a error on startup  and have no geSuit functions
Error is 

> 13:57:51 [INFO] §aStarting geSuit
> 13:57:51 [INFO] §aInitialising Managers
> 13:57:52 [INFO] Current Version of the Players Database: 2
> 13:57:52 [INFO] Current Version of the Homes Database: 2
> 13:57:52 [INFO] Current Version of the Ban Database: 2
> 13:57:52 [WARNING] 
> java.lang.ExceptionInInitializerError
>     at net.cubespace.geSuit.geSuit.onEnable(geSuit.java:36)
>     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:203)
>     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:205)
>     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:65)
> Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to net.cubespace.geSuit.configs.SubConfig.AnnouncementEntry
>     at net.cubespace.geSuit.managers.AnnouncementManager.loadAnnouncements(AnnouncementManager.java:26)
>     at net.cubespace.geSuit.managers.DatabaseManager.<clinit>(DatabaseManager.java:40)
>     ... 4 more

Thanks JamieKG

**Comment by geNAZt** [comment]
Yamler 2.2.1 and regenerate all configs fixes that Issue
