### ISSUE TITLE
Homes won't import from Essentials.

### ISSUE THREAD

**Issue by Absentee23** [Cube-Space/geSuit#2]
Importing homes from Essentials doesn't work for me, and it's kind of crucial. Running the command returns the following errors from bungee, this is two out of who knows how many of these blocks of text, likely one for each player:
http://pastebin.com/sxEyFrMS

I just did /importhomes and and it tells me the amount of homes and what was imported, except it never does, just starts with the above messages right after saying how many there were.

Thanks a lot for picking up this plugin/suite!

**Comment by Absentee23** [comment]
This is the result of running the command from the server console, also repeating similarly.
http://pastebin.com/7XUgXk6y

**Comment by geNAZt** [comment]
You tried to run the import when no Player was online on that Server. It must be at least one Player online for geSuit to function

**Comment by Absentee23** [comment]
OK, I think that is what the second pastebin error was, but the error in the first post is happening with one person on the server, myself. The error in the first pastebin is the one received in the bungeecord console when running /importhomes from the console on the spigot server. I was the only person logged in on the server. It shows the message "XX homes imported" in the spigot console and all that, but nothing is ever imported and the bungee console shows the error in the first post.
