### ISSUE TITLE
[Question] geSuit Homes

### ISSUE THREAD

**Issue by IlPicasso** [Cube-Space/geSuit#26]
I am thinking on migrating to geSuitHomes.

Actually, I have 7 servers, each server has the ability to /sethome.

Do I have to put /importhomes in each server.

Will I have trouble since each server default name for /home is home?

Thanks!

**Comment by geNAZt** [comment]
You currently are on Essentials ?

And yes if a home has duplicate Names in the Network it would cause trouble since geSuitHomes does not support Server based  Homes

**Comment by IlPicasso** [comment]
Yes I am currently on essentials.

In essentials every home has a default name which is "home" , I guess that will be a problem if I import the homes from essnetials to gesutihome

**Comment by geNAZt** [comment]
Correct

**Comment by IlPicasso** [comment]
So this is now fixed in the new build?

**Comment by geNAZt** [comment]
Yes this should be possible now
