### ISSUE TITLE
Getting errors in log on bungee starting

### ISSUE THREAD

**Issue by JamieKG** [Cube-Space/geSuit#3]
Hi I get the following when restarting bungee

> 15:40:36 [INFO] §aStarting geSuit
> 15:40:36 [INFO] §aInitialising Managers
> 15:40:36 [INFO] Current Version of the Players Database: 1
> 15:40:36 [INFO] Could not update the Player Database to version 2
> 15:40:36 [SEVERE] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'uuid'
> 15:40:36 [SEVERE]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 15:40:36 [SEVERE]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
> 15:40:36 [SEVERE]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 15:40:36 [SEVERE]   at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.Util.getInstance(Util.java:386)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4237)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2617)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2778)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2819)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2768)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:949)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:795)
> 15:40:36 [SEVERE]   at net.cubespace.geSuit.database.Players.checkUpdate(Players.java:199)
> 15:40:36 [SEVERE]   at net.cubespace.geSuit.database.ConnectionPool.initialiseConnections(ConnectionPool.java:88)
> 15:40:36 [SEVERE]   at net.cubespace.geSuit.managers.DatabaseManager.<clinit>(DatabaseManager.java:38)
> 15:40:36 [SEVERE]   at net.cubespace.geSuit.geSuit.onEnable(geSuit.java:33)
> 15:40:36 [SEVERE]   at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:203)
> 15:40:36 [SEVERE]   at net.md_5.bungee.BungeeCord.start(BungeeCord.java:205)
> 15:40:36 [SEVERE]   at net.md_5.bungee.Bootstrap.main(Bootstrap.java:65)
> 15:40:36 [INFO] Current Version of the Homes Database: 1
> 15:40:36 [SEVERE] java.sql.SQLException: Error on rename of './eg_gesuit/homes' to './eg_gesuit/#sql2-1185-5c94' (errno: 152)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1086)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4237)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2617)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2778)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2819)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2768)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:949)
> 15:40:36 [SEVERE]   at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:795)
> 15:40:36 [SEVERE]   at net.cubespace.geSuit.database.Homes.checkUpdate(Homes.java:152)
> 15:40:36 [SEVERE]   at net.cubespace.geSuit.database.ConnectionPool.initialiseConnections(ConnectionPool.java:88)
> 15:40:36 [SEVERE]   at net.cubespace.geSuit.managers.DatabaseManager.<clinit>(DatabaseManager.java:38)
> 15:40:36 [SEVERE]   at net.cubespace.geSuit.geSuit.onEnable(geSuit.java:33)
> 15:40:36 [SEVERE]   at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:203)
> 15:40:36 [SEVERE]   at net.md_5.bungee.BungeeCord.start(BungeeCord.java:205)
> 15:40:36 [SEVERE]   at net.md_5.bungee.Bootstrap.main(Bootstrap.java:65)
> 15:40:36 [INFO] Current Version of the Ban Database: 2
> 15:40:36 [INFO] Enabled plugin geSuit version 0.4.4b-24 by geNAZt

Thanks JamieKG

**Comment by geNAZt** [comment]
Did you regenerate the config.yml ? If so be sure that the Player, Homes and Bans database is on Version 2

**Comment by geNAZt** [comment]
Fixed the issue when you regenerate the Config. Config regeneration should now not cause that Errors

**Comment by JamieKG** [comment]
all I do is restart bungeecord and I get that error ive not touched the config since putting mysql in there

**Comment by geNAZt** [comment]
Should be fixed by that commit. Also be sure that the Database versions are correct now and the Error should be gone
