### ISSUE TITLE
Lava portals damage players when touching or going through them.

### ISSUE THREAD

**Issue by Absentee23** [Cube-Space/geSuit#30]
Title pretty much explains it. Getting too close, or going through a lava portal hurts players.

portal created with command `/setportal netherportal warp netherportal LAVA` (yes, the portal name and warp name are the same on purpose)

**Comment by geNAZt** [comment]
https://github.com/Cube-Space/geSuitPortals/commit/bf281e56516af2bdc2a7c857d77b332d8eb409d3

**Comment by Absentee23** [comment]
Still not fixed. The lava isn't damaging players, but it still lights them on fire. They don't receive fire damage for the first few seconds, then are damaged by burning for a few seconds before the fire goes out. Possible to cancel players getting lit on fire from portal lava? I think that would solve it.

Issue was more pronounced when warping to a different world, the slight lag warping to a different world (compared to warping to a closed room very nearby the original warp point) seemed to keep them in the lava portal for an extra second, then they are lit on fire.

**Comment by geNAZt** [comment]
Well the problem is that Fire handling from Lava is currently broken in Bukkit. This is the best i can do for now until its fixed in Bukkit
