### ISSUE TITLE
[Feature Request] player name lock-in (for upcoming name-change apocalypse)

### ISSUE THREAD

**Issue by Absentee23** [Cube-Space/geSuit#31]
Obviously you know about the upcoming abilities for people to change their names. This will break many other plugins that rely on names and may not be updated in time (or ever) to support UUIDs and name changes.

For example, I use Lockette (sign/NAME based chest locking) on one server, which I am kind of doubtful will update for UUIDs (it hasn't been updated for years, not that it needs it yet). If a player locks their chests, then changes their name and comes back, they will be permanently locked out of their chests. If another new player that has never joined before happens to join with an identical name as someone else, they will have access to their chests. I dunno why I'm explaining this, I'm sure you know how it will work, but I want to illustrate my point.

Other people have created plugins to lock people to a certain player name and block them from joining with a different name. I think a better solution would be if an existing player changes their name, to forcibly change a persons name back to what it was when they first joined the server, **in a way that all other plugins & the server recognize that as their player name**, not just a nickname. Also append a _2, _3, etc if people join with a name identical to a player that already exists on the server. Include a notification of this happening (configurable in Messages.yml) to the player and admins as well.

Add an option to enable/disable (default disabled) this, of course. Maybe a _console_ command /setrealname <UUID> <name to set> (console command, using UUID because the intention would be to set this ONCE, in outlier cases where the appended _2 isn't acceptable to someone.)

This would GREATLY reduce problems that will arise from the coming name-change apocalypse, and allow many servers that are using plugins that may not update right away (or ever) to continue running smoothly, all without having to add yet another plugin. I _think_ handling it from the bungee end could reduce the chance of other problems as well, especially with other bungee plugins.

**Comment by geNAZt** [comment]
Erm no. Plugins should update to UUIDs properly since this is nothing which is impossible. I will not support manipulating Player data (and realname changes are not possible at all) just because another Plugin may break with it.

If you want to force your Players to stay on their name use OneUUID which kicks the Players when they changed their Name.
