### ISSUE TITLE
[Low Priority] Documentation fix

### ISSUE THREAD

**Issue by TheLecturer** [Cube-Space/geSuit#35]
Documentation on this page - http://www.spigotmc.org/resources/gesuitbans.396/ - needs to be updated.

Commands section  > tempban
Time format needs to change from 

```
d:(days) h:(hours) m:(minutes)
```

to

```
2d2h2m2s (for example)
```

Thanks.

**Comment by geNAZt** [comment]
Its updated in the Resource. Thx
