### ISSUE TITLE
warps ignore yaw

### ISSUE THREAD

**Issue by JamieKG** [Cube-Space/geSuit#4]
Hi when I use a warp it always leaves me facing south

Thanks JamieKG

**Comment by geNAZt** [comment]
Is the Database entry correct ? Or does it fail to save the yaw in it ?

**Comment by JamieKG** [comment]
its in the database its just when you do /warp <warpname> it dont seem to take yaw direction into account

**Comment by geNAZt** [comment]
Fixed in https://github.com/Cube-Space/geSuitTeleport/commit/3384287183df8c6d6a37ccfb7965bbf8d07be990
