### ISSUE TITLE
How to disable a command (urgent)

### ISSUE THREAD

**Issue by IlPicasso** [Cube-Space/geSuit#42]
Hi! Well, for some reason something is executing the command kickall, which is kicking all my players <.< and the console is launching it, I want to disable the command completely. How I can do it?

**Comment by jimmikaelkael** [comment]
AFAIK, you can't with this version... Maybe you can remove geSuitBans from the spigot instance, to see if it solves the problem.

**Comment by IlPicasso** [comment]
I managed to fix this,

I removed the command kickall from the plugin.yml that are in the instances which run RemoteToolkit, 

RemoteToolkit executed the Command kickall to restart the server of HungerGames and SkyBlock every 5 hours

I can close this 

Thanks :+1:
