### ISSUE TITLE
Can't import homes

### ISSUE THREAD

**Issue by huxcrux** [Cube-Space/geSuit#47]
I try to run import homes but i just got error.

21:36:00 [INFO] bl0m1 issued server command: /importhomes
21:36:00 [SEVERE] null
21:36:00 org.bukkit.command.CommandException: Unhandled exception executing command 'importhomes' in plugin geSuitHomes v0.1.1b-5
21:36:00    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1465]
21:36:00    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180) ~[spigot.jar:git-Spigot-1465]
21:36:00    at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServer.java:728) ~[spigot.jar:git-Spigot-1465]
21:36:00    at net.minecraft.server.v1_7_R3.PlayerConnection.handleCommand(PlayerConnection.java:985) [spigot.jar:git-Spigot-1465]
21:36:00    at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:830) [spigot.jar:git-Spigot-1465]
21:36:00    at net.minecraft.server.v1_7_R3.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1465]
21:36:00    at net.minecraft.server.v1_7_R3.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1465]
21:36:00    at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:180) [spigot.jar:git-Spigot-1465]
21:36:00    at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1465]
21:36:00    at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:713) [spigot.jar:git-Spigot-1465]
21:36:00    at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:283) [spigot.jar:git-Spigot-1465]
21:36:00    at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:576) [spigot.jar:git-Spigot-1465]
21:36:00    at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:482) [spigot.jar:git-Spigot-1465]
21:36:00    at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1465]
21:36:00 Caused by: java.lang.NullPointerException
21:36:00    at net.cubespace.geSuitHomes.managers.HomesManager.setHome(HomesManager.java:141) ~[?:?]
21:36:00    at net.cubespace.geSuitHomes.managers.HomesManager.importHomes(HomesManager.java:85) ~[?:?]
21:36:00    at net.cubespace.geSuitHomes.commands.ImportHomesCommand.onCommand(ImportHomesCommand.java:14) ~[?:?]
21:36:00    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1465]
21:36:00    ... 13 more

**Comment by gh0ztbuster** [comment]
Same here
