### ISSUE TITLE
UDID "Null"

### ISSUE THREAD

**Issue by DylanBryanRoss** [Cube-Space/geSuit#49]
Hello,

I run an Attack of the BTeam (1.6.4) server. Recently, I switched over from BungeeSuite as it is becoming outdated and moved over to GeSuit, I converted my database of 86,000 users in about 3 minutes. Everything moved over properly, but it never grabbed UDID's of the players.. It just filled that row in with "null"

The BungeeCord console is also displaying UDID's as Null.

How would I go about fixing this issue? I am running the latest version of GeSuit.

Regards,
Dylan

**Comment by geNAZt** [comment]
Its 1.6.4 there are no uuuds
