### ISSUE TITLE
the command /spawn has no affect

### ISSUE THREAD

**Issue by JamieKG** [Cube-Space/geSuit#5]
I seems the command /spawn has no affect you see I have issued that command in the server but there is no error or feedback and you are not sent to the server or world spawn you have set

Thanks JamieKG

**Comment by geNAZt** [comment]
Do you have geSuitTeleport installed ?

**Comment by JamieKG** [comment]
yes  /serverspawn and /worldspawn work

**Comment by geNAZt** [comment]
Are you sure the permissions are set correctly ?

World spawn: gesuit.spawns.spawn.world
Server spawn: gesuit.spawns.spawn.server

**Comment by JamieKG** [comment]
ok sorry yes it was a perm issue
