### ISSUE TITLE
Using /tp (player) (Otherplayer) sends  to the wrong player

### ISSUE THREAD

**Issue by IlPicasso** [Cube-Space/geSuit#7]
As the title says

http://gyazo.com/d8f7f29c05b1bbd8c6ba8c990e5c83a7

Also you can see something is going wrong with GeSuit ^^

I reported it already

In the Picture you will see how I am using /tp Il_Picasso Roy and it is sending me to DaxtroyBlaze

**Comment by geNAZt** [comment]
Its le fixed: https://github.com/Cube-Space/geSuit/commit/599b533fe4d93b4893bd0b08457a5c022f6548e4
