### ISSUE TITLE
Leave messages not appearing

### ISSUE THREAD

**Issue by CTMiner** [Cube-Space/geSuit#9]
I have BroadcastProxyConnectionMessages on in my config, but I'm not getting player disconnect messages. I am using latest geSuit. Any ideas?

**Comment by geNAZt** [comment]
Do you get any errors when it does not show the message ?

**Comment by CTMiner** [comment]
None. I'm going to try manually updating later and see if it just failed to update or something. I'll let you know how it goes.

**Comment by Kait18** [comment]
I also have the same Issue, and there are also no errors. I'm using the latest dev build.

**Comment by CTMiner** [comment]
I am on latest version (checked). Sorry that took so long to reply to, I was locked out of the server for a couple days.

**Comment by geNAZt** [comment]
Should be fixed in 0.7.1
